[features]
seeds = false
skip-lint = false
[programs.localnet]
single_asset_lending_program = "F5dLpWLFYuEGEZZNf2RQt8sJnr5mzgpDhY3npuz8JggS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/quellen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
